# User config
author: "Anuj Natraj"
tagline: "Anuj Natraj's Portfolio"
description: "Current student in M.S. in Robotics program in Northwestern University."
keywords: "ROS, Robotics, Perception"
email: "natraj.anuj@gmail.com"
linkedin: "https://www.linkedin.com/in/anuj-natraj-27217b18a/"
github: "https://github.com/AnujN9"
resume: "https://drive.google.com/file/d/1W5EH4ChW78SEYoDqHxxD6xpSGmRIsbG6/view?usp=drive_link"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed